name: Main Data
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: samsanchez-ctrl
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: samsanchez-ctrl/database_devops:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Private EC2 via SSH Proxy
        uses: appleboy/ssh-action@master
        with:
          host: 10.0.153.106           # IP Privada Data
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: 10.0.137.129 # Uso el Backend como puente
          proxy_username: ec2-user
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull samsanchez-ctrl/database_devops:latest
            sudo docker stop database_devops || true
            sudo docker rm database_devops || true
            sudo docker run -d --name database_devops -p 3306:3306 \
              -e MYSQL_DATABASE=tienda_perritos \
              -e MYSQL_USER=alumno \
              -e MYSQL_PASSWORD=alumno123 \
              -e MYSQL_ROOT_PASSWORD=root_password \
              samsanchez-ctrl/database_devops:latest